services:
  pico_devcontainer_template:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      # 現在のディレクトリをコンテナの/workspaceにマウント
      - .:/workspace
      # デバイスアクセス用
      - /dev:/dev
    ports:
      - "3000:3000"
    privileged: true
    environment:
      - PROJECT_NAME
    network_mode: host
