services:
  pico_devcontainer_template:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
      args:
        USER_ID: ${LOCAL_UID}
        GROUP_ID: ${LOCAL_GID}
    volumes:
      # 現在のディレクトリをコンテナの/workspaceにマウント
      - .:/workspace
